### ISSUE TITLE
Examples do not compile in Modern Arduino IDE 2.3.6

### ISSUE THREAD

**Issue by matalog** [i-am-bigmike/HardwareSerial_flow_control#1]
When I compile one of the examples (Windows 10), or indeed just try to use Serial in the newest Arduino IDE 2.3.6, I get an error message and the code does not compile.

This code does not compile:

`

void setup() {

  Serial1.begin(9600);
}

void loop() {

 delay(1400);

    Serial1.write("abc2CBAZZABC2cba");

}`

It returns this error:

`C:\Users\-----\AppData\Local\Temp\ccsH6usT.ltrans0.ltrans.o: In function `begin':
C:\Users\-----\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6\cores\arduino/HardwareSerial.h:146: undefined reference to `HardwareSerial::begin(unsigned long, unsigned char, signed char, signed char)'
collect2.exe: error: ld returned 1 exit status
exit status 1

Compilation error: exit status 1`

To be clear, I can get this to work in an older version of Arduino that I still have installed 1.8.13 - and it works well.  It seems that both versions of Arduino on my PC use the 7 serial files at the same location.

Is there any way to get it working in Arduino IDE 2.3.6?
